import bcrypt from 'bcryptjs';

const data = {
  
  
    users: [
      {
        name: 'Nayab',
        email: 'admin@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: true,
      },
      {
        name: 'Bobby',
        email: 'user@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: false,
      },
    ],
  products: [
    {
      name: 'French Wine 1',
      slug: 'french-wine1',
      category: 'Wine',
      image: '/images/wine1.jpg',
      price: 70,
      brand: 'French',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular wine',
    },
    {
      name: 'French Wine 2',
      slug: 'french-wine2',
      category: 'Wine',
      image: '/images/wine2.jpg',
      price: 80,
      brand: 'French',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular wine',
    },
    {
      name: 'Italian Wine 1',
      slug: 'italian-Wine1',
      category: 'Wine',
      image: '/images/wine6.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular wine',
    },
    {
      name: 'Italian Wine 2',
      slug: 'italian-wine2',
      category: 'wine',
      image: '/images/wine14.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasty wine',
    },
    {
      name: 'Spanish Wine 1',
      slug: 'spanish-wine1',
      category: 'wine',
      image: '/images/wine5.jpg',
      price: 95,
      brand: 'Spanish',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular spanish wine',
    },
    {
      name: 'Spanish Wine 2',
      slug: 'spanish-wine2',
      category: 'wine',
      image: '/images/wine8.jpg',
      price: 75,
      brand: 'Toledo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular wine',
    },
     {
      name: 'Croatian Wine',
      slug: 'croatian-wine',
      category: 'wine',
      image: '/images/wine7.jpg',
      price: 95,
      brand: 'Split',
      rating: 4.7,
      numReviews: 7,
      countInStock: 30,
      description: 'A popular wine',
    },
  ],
};
export default data;